version: '3.1'
services:
    db:
        image: mariadb
        restart: always
        ports:
            - 3306
        environment:
            MYSQL_ROOT_PASSWORD: Horde
        networks:
            - horde
    php:
        image: registry.opensuse.org/isv/b1-systems/horde5/containers/opensuse/tumbleweed/container/opensuse/tumbleweed:current
        ports:
            - 80:80
        networks:
            - horde
        depends_on:
            - "db"
        tty: true

networks:
    horde:
        driver: bridge
